name: Code static analysis
description: "builds and uploads flutter apk for a release"

inputs:
  dart-define:
    description: "Dart defines for the build"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1

    - uses: actions/setup-java@v1
      with:
        java-version: "12.x"

    - id: cmd
      shell: bash
      run: |
        cd ./app
        version=$(grep "version: " pubspec.yaml | awk -F" " '{print $2}' | tr -d '\n')
        flutter clean
        flutter pub get
        flutter build apk --target=lib/main/main.dart --release --build-name=$version --dart-define=${{ inputs.dart-define }}
        echo "directory=$version" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/$version"
        cp -r build/app/outputs/flutter-apk/* "$GITHUB_WORKSPACE/$version"
        ls -R

    - name: Upload appbundle
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ steps.cmd.outputs.directory }} # should be the version for this build
        path: ${{ steps.cmd.outputs.directory }}
