name: Flutter CI

on:
  workflow_dispatch:
  push:

jobs:
  install-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

  analyze:
    runs-on: ubuntu-latest
    needs: install-flutter
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/analyze

  test:
    runs-on: ubuntu-latest
    needs: install-flutter
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
